export const Articles = [
  {
    'id': 7712,
    'short_id': null,
    'user_id': 2,
    'topic_id': 20,
    'type': 'feed',
    'link': 'http://next.36kr.com/posts/34217',
    'title': '阳淘 3.0',
    'summary': '',
    'image_url': '',
    'location': '',
    'longitude': 0,
    'latitude': 0,
    'upvote_count': 0,
    'downvote_count': 0,
    'view_count': 0,
    'comment_count': 0,
    'published_at': '2016-10-16 00:27:44',
    'voted': false,
    'user': {
      'id': 2,
      'username': 'hidazaio',
      'email': 'hi@daza.io',
      'name': 'hi@daza.io',
      'real_name': '',
      'avatar_url': 'http://obryq3mj0.bkt.clouddn.com/user/2/r1jRh406.png',
      'use_gravatar': false,
      'age': 0,
      'gender': 'unspecified',
      'birthday': '',
      'city': '深圳',
      'company': '',
      'website': 'http://daza.io',
      'bio': '[daza.io] 用于管理订阅主题的账号',
      'site_admin': false,
      'followers_count': 0,
      'following_count': 0,
      'topic_count': 0,
      'article_count': 0,
      'created_at': '2016-10-02 15:33:00',
      'updated_at': '2016-10-02 15:52:54',
      'followed': false
    },
    'topic': {
      'id': 20,
      'short_id': 'Sk8Lfqf0',
      'user_id': 2,
      'category_id': 9,
      'name': '36氪NEXT',
      'slug': null,
      'type': 'feed',
      'website': 'http://next.36kr.com',
      'image_url': 'http://obryq3mj0.bkt.clouddn.com/topic/Sk8Lfqf0/r1lk7qz0.jpg',
      'description': '发现、分享和讨论新产品',
      'source_format': 'atom+xml',
      'source_link': 'http://next.36kr.com/feed',
      'article_count': 0,
      'subscriber_count': 1,
      'created_at': '2016-10-05 22:48:59',
      'updated_at': '2016-10-05 22:48:59',
      'subscribed': false
    },
    'tags': []
  },
  {
    'id': 7714,
    'short_id': null,
    'user_id': 2,
    'topic_id': 20,
    'type': 'feed',
    'link': 'http://next.36kr.com/posts/34237',
    'title': '安静地脑补',
    'summary': '',
    'image_url': '',
    'location': '',
    'longitude': 0,
    'latitude': 0,
    'upvote_count': 0,
    'downvote_count': 0,
    'view_count': 0,
    'comment_count': 0,
    'published_at': '2016-10-16 00:19:48',
    'voted': false,
    'user': {
      'id': 2,
      'username': 'hidazaio',
      'email': 'hi@daza.io',
      'name': 'hi@daza.io',
      'real_name': '',
      'avatar_url': 'http://obryq3mj0.bkt.clouddn.com/user/2/r1jRh406.png',
      'use_gravatar': false,
      'age': 0,
      'gender': 'unspecified',
      'birthday': '',
      'city': '深圳',
      'company': '',
      'website': 'http://daza.io',
      'bio': '[daza.io] 用于管理订阅主题的账号',
      'site_admin': false,
      'followers_count': 0,
      'following_count': 0,
      'topic_count': 0,
      'article_count': 0,
      'created_at': '2016-10-02 15:33:00',
      'updated_at': '2016-10-02 15:52:54',
      'followed': false
    },
    'topic': {
      'id': 20,
      'short_id': 'Sk8Lfqf0',
      'user_id': 2,
      'category_id': 9,
      'name': '36氪NEXT',
      'slug': null,
      'type': 'feed',
      'website': 'http://next.36kr.com',
      'image_url': 'http://obryq3mj0.bkt.clouddn.com/topic/Sk8Lfqf0/r1lk7qz0.jpg',
      'description': '发现、分享和讨论新产品',
      'source_format': 'atom+xml',
      'source_link': 'http://next.36kr.com/feed',
      'article_count': 0,
      'subscriber_count': 1,
      'created_at': '2016-10-05 22:48:59',
      'updated_at': '2016-10-05 22:48:59',
      'subscribed': false
    },
    'tags': []
  },
  {
    'id': 7710,
    'short_id': null,
    'user_id': 2,
    'topic_id': 20,
    'type': 'feed',
    'link': 'http://next.36kr.com/posts/34228',
    'title': 'Adguard Pro',
    'summary': '',
    'image_url': '',
    'location': '',
    'longitude': 0,
    'latitude': 0,
    'upvote_count': 0,
    'downvote_count': 0,
    'view_count': 0,
    'comment_count': 0,
    'published_at': '2016-10-16 00:16:25',
    'voted': false,
    'user': {
      'id': 2,
      'username': 'hidazaio',
      'email': 'hi@daza.io',
      'name': 'hi@daza.io',
      'real_name': '',
      'avatar_url': 'http://obryq3mj0.bkt.clouddn.com/user/2/r1jRh406.png',
      'use_gravatar': false,
      'age': 0,
      'gender': 'unspecified',
      'birthday': '',
      'city': '深圳',
      'company': '',
      'website': 'http://daza.io',
      'bio': '[daza.io] 用于管理订阅主题的账号',
      'site_admin': false,
      'followers_count': 0,
      'following_count': 0,
      'topic_count': 0,
      'article_count': 0,
      'created_at': '2016-10-02 15:33:00',
      'updated_at': '2016-10-02 15:52:54',
      'followed': false
    },
    'topic': {
      'id': 20,
      'short_id': 'Sk8Lfqf0',
      'user_id': 2,
      'category_id': 9,
      'name': '36氪NEXT',
      'slug': null,
      'type': 'feed',
      'website': 'http://next.36kr.com',
      'image_url': 'http://obryq3mj0.bkt.clouddn.com/topic/Sk8Lfqf0/r1lk7qz0.jpg',
      'description': '发现、分享和讨论新产品',
      'source_format': 'atom+xml',
      'source_link': 'http://next.36kr.com/feed',
      'article_count': 0,
      'subscriber_count': 1,
      'created_at': '2016-10-05 22:48:59',
      'updated_at': '2016-10-05 22:48:59',
      'subscribed': false
    },
    'tags': []
  },
  {
    'id': 7711,
    'short_id': null,
    'user_id': 2,
    'topic_id': 20,
    'type': 'feed',
    'link': 'http://next.36kr.com/posts/34227',
    'title': '蜜书社',
    'summary': '',
    'image_url': '',
    'location': '',
    'longitude': 0,
    'latitude': 0,
    'upvote_count': 0,
    'downvote_count': 0,
    'view_count': 0,
    'comment_count': 0,
    'published_at': '2016-10-16 00:10:08',
    'voted': false,
    'user': {
      'id': 2,
      'username': 'hidazaio',
      'email': 'hi@daza.io',
      'name': 'hi@daza.io',
      'real_name': '',
      'avatar_url': 'http://obryq3mj0.bkt.clouddn.com/user/2/r1jRh406.png',
      'use_gravatar': false,
      'age': 0,
      'gender': 'unspecified',
      'birthday': '',
      'city': '深圳',
      'company': '',
      'website': 'http://daza.io',
      'bio': '[daza.io] 用于管理订阅主题的账号',
      'site_admin': false,
      'followers_count': 0,
      'following_count': 0,
      'topic_count': 0,
      'article_count': 0,
      'created_at': '2016-10-02 15:33:00',
      'updated_at': '2016-10-02 15:52:54',
      'followed': false
    },
    'topic': {
      'id': 20,
      'short_id': 'Sk8Lfqf0',
      'user_id': 2,
      'category_id': 9,
      'name': '36氪NEXT',
      'slug': null,
      'type': 'feed',
      'website': 'http://next.36kr.com',
      'image_url': 'http://obryq3mj0.bkt.clouddn.com/topic/Sk8Lfqf0/r1lk7qz0.jpg',
      'description': '发现、分享和讨论新产品',
      'source_format': 'atom+xml',
      'source_link': 'http://next.36kr.com/feed',
      'article_count': 0,
      'subscriber_count': 1,
      'created_at': '2016-10-05 22:48:59',
      'updated_at': '2016-10-05 22:48:59',
      'subscribed': false
    },
    'tags': []
  },
  {
    'id': 7713,
    'short_id': null,
    'user_id': 2,
    'topic_id': 20,
    'type': 'feed',
    'link': 'http://next.36kr.com/posts/34235',
    'title': 'Amazon Music Unlimited',
    'summary': '',
    'image_url': '',
    'location': '',
    'longitude': 0,
    'latitude': 0,
    'upvote_count': 0,
    'downvote_count': 0,
    'view_count': 0,
    'comment_count': 0,
    'published_at': '2016-10-16 00:08:07',
    'voted': false,
    'user': {
      'id': 2,
      'username': 'hidazaio',
      'email': 'hi@daza.io',
      'name': 'hi@daza.io',
      'real_name': '',
      'avatar_url': 'http://obryq3mj0.bkt.clouddn.com/user/2/r1jRh406.png',
      'use_gravatar': false,
      'age': 0,
      'gender': 'unspecified',
      'birthday': '',
      'city': '深圳',
      'company': '',
      'website': 'http://daza.io',
      'bio': '[daza.io] 用于管理订阅主题的账号',
      'site_admin': false,
      'followers_count': 0,
      'following_count': 0,
      'topic_count': 0,
      'article_count': 0,
      'created_at': '2016-10-02 15:33:00',
      'updated_at': '2016-10-02 15:52:54',
      'followed': false
    },
    'topic': {
      'id': 20,
      'short_id': 'Sk8Lfqf0',
      'user_id': 2,
      'category_id': 9,
      'name': '36氪NEXT',
      'slug': null,
      'type': 'feed',
      'website': 'http://next.36kr.com',
      'image_url': 'http://obryq3mj0.bkt.clouddn.com/topic/Sk8Lfqf0/r1lk7qz0.jpg',
      'description': '发现、分享和讨论新产品',
      'source_format': 'atom+xml',
      'source_link': 'http://next.36kr.com/feed',
      'article_count': 0,
      'subscriber_count': 1,
      'created_at': '2016-10-05 22:48:59',
      'updated_at': '2016-10-05 22:48:59',
      'subscribed': false
    },
    'tags': []
  },
  {
    'id': 7358,
    'short_id': '-foPSpQ',
    'user_id': 2,
    'topic_id': 20,
    'type': 'feed',
    'link': 'http://next.36kr.com/posts/34225',
    'title': 'Looks',
    'summary': '',
    'image_url': '',
    'location': '',
    'longitude': 0,
    'latitude': 0,
    'upvote_count': 0,
    'downvote_count': 0,
    'view_count': 2,
    'comment_count': 0,
    'published_at': '2016-10-15 23:47:14',
    'voted': false,
    'user': {
      'id': 2,
      'username': 'hidazaio',
      'email': 'hi@daza.io',
      'name': 'hi@daza.io',
      'real_name': '',
      'avatar_url': 'http://obryq3mj0.bkt.clouddn.com/user/2/r1jRh406.png',
      'use_gravatar': false,
      'age': 0,
      'gender': 'unspecified',
      'birthday': '',
      'city': '深圳',
      'company': '',
      'website': 'http://daza.io',
      'bio': '[daza.io] 用于管理订阅主题的账号',
      'site_admin': false,
      'followers_count': 0,
      'following_count': 0,
      'topic_count': 0,
      'article_count': 0,
      'created_at': '2016-10-02 15:33:00',
      'updated_at': '2016-10-02 15:52:54',
      'followed': false
    },
    'topic': {
      'id': 20,
      'short_id': 'Sk8Lfqf0',
      'user_id': 2,
      'category_id': 9,
      'name': '36氪NEXT',
      'slug': null,
      'type': 'feed',
      'website': 'http://next.36kr.com',
      'image_url': 'http://obryq3mj0.bkt.clouddn.com/topic/Sk8Lfqf0/r1lk7qz0.jpg',
      'description': '发现、分享和讨论新产品',
      'source_format': 'atom+xml',
      'source_link': 'http://next.36kr.com/feed',
      'article_count': 0,
      'subscriber_count': 1,
      'created_at': '2016-10-05 22:48:59',
      'updated_at': '2016-10-05 22:48:59',
      'subscribed': false
    },
    'tags': []
  }
];
